### ISSUE TITLE
no lib folder when imported via npm

### ISSUE THREAD

**Issue by Chexpir** [brandonhorst/elliptical-string#1]
All other libraries like lacone-phrase-datetime or lacone-phrase-number are compiling correctly automatically when npm install is done. Not this one. I can't see any error.
node 4.2.1 (I've also tried 0.1.0.26)

**Comment by brandonhorst** [comment]
Thanks. Fixed with https://github.com/lacona/lacona-phrase-string/commit/ee1b5ff4c0d03ddd809812d857444d40e8234694. Sorry about that.
